### PR TITLE
fix: the runtime error: event loop is closed

### PR DESCRIPTION
**Pull request by morningdip**
Fix the runtime error: event loop is closed

### CODE REVIEW

**Comment by istudyatuni** [comment]
Thank you! Do you mind if I do a squash merge?

**Comment by morningdip** [comment]
Sure!

**Comment by istudyatuni** [comment]
`get_event_loop()` is [deprecated](https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop) since python 3.10. I also got the warning: `DeprecationWarning: There is no current event loop`, so since there are no other async loops here, I think it's better to use [`new_event_loop()`](https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.new_event_loop), what do you think?

**Comment by morningdip** [comment]
Oops, I hadn’t noticed that.
So maybe the solution is more like this.

```python
loop = new_event_loop()
set_event_loop(loop)
loop.run_until_complete(process_list(*result))
```

Thanks!

**Comment by istudyatuni** [comment]
Why do we need `set_event_loop` if on the next line this loop called directly?

Upd. I think I understand why.

If you want you can do it in this PR (I hope I can merge it after)

**Comment by morningdip** [comment]
I don't think I can edit pull request once it is closed.
I'll create a new PR, thanks.

**Pull request merged**
